version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - .config:/config
      - ./custom_components:/config/custom_components
    environment:
      - TZ=America/New_York
    restart: always
    ports:
      - 8123:8123
    network_mode: "bridge"
